version: 2

updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "devolutions/lucid-maintainers"      
    # Disable version updates, we only want security updates.
    open-pull-requests-limit: 0