trigger:
  - master

pr:
  - master

stages:
  - stage: RustCodeFormattingCheck
    dependsOn: [ ]
    jobs:
      - job:
        displayName: 'Check Rust'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - script: |
              rustup update
            displayName: "Install rust"
          - script: |
              cargo fmt --all -- --check
            displayName: "Check Format"
          - script: |
              cargo clippy -- --D warnings
            displayName: "Check Clippy"
  - stage: WebAssembly
    dependsOn: [ ]
    jobs:
      - job:
        displayName: 'Build & Pack Wasm'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - script: |
              rustup update
              cargo install wasm-pack
            displayName: "Update rust and install wasm-pack"
          - script: |
              sh ./wasm/build.sh
            displayName: "Generating npm package"
          - task: CopyFiles@2
            inputs:
              contents: 'dist/**'
              targetFolder: $(Build.ArtifactStagingDirectory)

          - task: PublishBuildArtifacts@1
            inputs:
              pathToPublish: $(Build.ArtifactStagingDirectory)
              artifactName: WebAssembly