[package]
name = "slauth"
version = "0.3.0"
authors = ["richer <richer.arc@gmail.com>"]
edition = "2018"
description = "oath HOTP and TOTP complient implementation"
documentation = "https://docs.rs/slauth"
homepage = "https://github.com/devolutions/slauth"
repository = "https://github.com/devolutions/slauth"
readme = "README.md"
keywords = ["TOTP", "HOTP", "2FA", "MFA"]
license = "MIT"

[target.'cfg(target_os="android")'.dependencies]
jni = { version = "0.12", default-features = false }

[lib]
name = "slauth"
crate-type = ["staticlib", "cdylib"]

[features]
default = ['native-bindings', 'u2f-server']
native-bindings = []
u2f-server = ['serde_json', 'webpki']

[dependencies]
sha2 = "0.8.0"
hmac = "0.7.0"
sha-1 = "0.8.1"
time = "0.1.42"
base32 = "0.4.0"
base64 = "0.10.1"
byteorder = "1.3.1"
ring = "0.14.6"
untrusted = "0.6.2"
hashbrown = "0.4.0"
serde = "1.0.92"
serde_repr = "0.1.4"
serde_derive = "1.0.92"

serde_json = { version = "1.0.39", optional = true }
webpki = { version = "0.19.1", optional = true }

[dev-dependencies]
hex = "0.3.2"
serde_json = "1.0.39"