#![allow(dead_code)]

pub const CLASS_BYTE_DEFAULT: u8 = 0x00;

pub const REGISTER_COMMAND_CODE: u8 = 0x01;
pub const AUTHENTICATE_COMMAND_CODE: u8 = 0x02;
pub const VERSION_COMMAND_CODE: u8 = 0x03;
pub const VENDOR_FIRST_COMMAND_CODE: u8 = 0x40;
pub const VENDOR_LAST_COMMAND_CODE: u8 = 0xBF;

pub const AUTHENTICATE_CHECK_ONLY: u8 = 0x07;
pub const AUTHENTICATE_ENFORCE_PRESENCE: u8 = 0x03;
pub const AUTHENTICATE_DONT_ENFORCE_PRESENCE: u8 = 0x08;

pub const SW_NO_ERROR: u16 = 0x9000;
pub const SW_CONDITION_NOT_SATISFIED: u16 = 0x6985;
pub const SW_WRONG_DATA: u16 = 0x6A80;
pub const SW_WRONG_LENGTH: u16 = 0x6700;
pub const SW_CLASS_NOT_SUPPORTED: u16 = 0x6E00;
pub const SW_COMMAND_NOT_SUPPORTED: u16 = 0x6D00;

pub const REGISTER_RESPONSE_RESERVED: u8 = 0x05;

pub const REGISTER_REQUEST_DATA_LEN: usize = 64;
pub const AUTHENTICATE_REQUEST_DATA_FIXED_LEN: usize = 34;
pub const MAX_RESPONSE_LEN_SHORT: usize = 256;
pub const MAX_RESPONSE_LEN_EXTENDED: usize = 65536;