pub const WEBAUTHN_CHALLENGE_LENGTH: usize = 32;
pub const WEBAUTHN_CREDENTIAL_ID_LENGTH: usize = 16;

pub const WEBAUTHN_COSE_ALGORITHM_IDENTIFIER_ES256: i64 = -7;
pub const WEBAUTHN_COSE_ALGORITHM_IDENTIFIER_RS256: i64 = -257;

pub const WEBAUTHN_USER_PRESENT_FLAG: u8 = 00000001;
pub const WEBAUTHN_USER_VERIFIED_FLAG: u8 = 00000100;

pub const WEBAUTHN_FORMAT_PACKED: &str = "packed";
pub const WEBAUTHN_FORMAT_FIDO_U2F: &str = "fido-u2f";