pub const WEBAUTHN_CHALLENGE_LENGTH: usize = 32;
pub const WEBAUTHN_CREDENTIAL_ID_LENGTH: usize = 16;

pub const WEBAUTHN_COSE_ALGORITHM_IDENTIFIER_ES256: i64 = -7;
pub const WEBAUTHN_COSE_ALGORITHM_IDENTIFIER_RS256: i64 = -257;